DATA_FILE_PATH: 'data/processed/merged_heart_data.csv'
TARGET_COLUMN: 'HeartDisease'
TEST_SIZE: 0.2
RANDOM_STATE: 12
param_grid:
  model__n_estimators: [50, 100, 200]
  model__max_depth: [None, 10, 20, 30]
  model__min_samples_split: [2, 5, 10]
  model__min_samples_leaf: [1, 2, 4]
  model__bootstrap: [True, False]
